### PR TITLE
PHP 8: add support

### PR DESCRIPTION
**Pull request by davidrans**
This adds support for PHP 8 and adds tests.

cr_req 1
qa_req 0

Connects https://github.com/iFixit/ifixit/issues/37333

### CODE REVIEW

**Comment by psalm-shepherd** [comment]
Psalm found errors in other files

```
src/Either.php:47:14 - Cannot reference $this in a pure context
src/Either.php:56:15 - Cannot reference $this in a pure context
src/Either.php:82:14 - Cannot reference $this in a pure context
src/Either.php:83:12 - Cannot reference $this in a pure context
src/Either.php:96:15 - Cannot reference $this in a pure context
src/Either.php:97:12 - Cannot reference $this in a pure context
src/Either.php:126:14 - Cannot reference $this in a pure context
src/Either.php:127:12 - Cannot reference $this in a pure context
src/Either.php:128:12 - Cannot call an impure function from a mutation-free context
src/Either.php:128:32 - Cannot reference $this in a pure context
src/Either.php:144:15 - Cannot reference $this in a pure context
src/Either.php:145:12 - Cannot reference $this in a pure context
src/Either.php:146:12 - Cannot call an impure function from a mutation-free context
src/Either.php:146:32 - Cannot reference $this in a pure context
src/Either.php:167:14 - Cannot reference $this in a pure context
src/Either.php:168:12 - Cannot reference $this in a pure context
src/Either.php:185:15 - Cannot reference $this in a pure context
src/Either.php:186:12 - Cannot reference $this in a pure context
src/Either.php:211:14 - Cannot reference $this in a pure context
src/Either.php:212:12 - Cannot reference $this in a pure context
src/Either.php:213:23 - Cannot call an impure function from a mutation-free context
src/Either.php:213:43 - Cannot reference $this in a pure context
src/Either.php:232:15 - Cannot reference $this in a pure context
src/Either.php:233:12 - Cannot reference $this in a pure context
src/Either.php:234:24 - Cannot call an impure function from a mutation-free context
src/Either.php:234:44 - Cannot reference $this in a pure context
src/Either.php:257:14 - Cannot reference $this in a pure context
src/Either.php:258:12 - Cannot reference $this in a pure context
src/Either.php:276:15 - Cannot reference $this in a pure context
src/Either.php:277:12 - Cannot reference $this in a pure context
src/Either.php:303:14 - Cannot reference $this in a pure context
src/Either.php:304:12 - Cannot reference $this in a pure context
src/Either.php:305:12 - Cannot call an impure function from a mutation-free context
src/Either.php:305:38 - Cannot reference $this in a pure context
src/Either.php:322:15 - Cannot reference $this in a pure context
src/Either.php:323:12 - Cannot reference $this in a pure context
src/Either.php:324:12 - Cannot call an impure function from a mutation-free context
src/Either.php:324:38 - Cannot reference $this in a pure context
src/Either.php:363:14 - Cannot reference $this in a pure context
src/Either.php:364:12 - Cannot call an impure function from a mutation-free context
src/Either.php:364:18 - Cannot reference $this in a pure context
src/Either.php:365:12 - Cannot call an impure function from a mutation-free context
src/Either.php:365:19 - Cannot reference $this in a pure context
src/Either.php:388:12 - Cannot reference $this in a pure context
src/Either.php:392:7 - Cannot call an impure function from a mutation-free context
src/Either.php:392:13 - Cannot reference $this in a pure context
src/Either.php:415:11 - Cannot reference $this in a pure context
src/Either.php:419:7 - Cannot call an impure function from a mutation-free context
src/Either.php:419:14 - Cannot reference $this in a pure context
src/Either.php:462:14 - Cannot reference $this in a pure context
src/Either.php:497:14 - Cannot reference $this in a pure context
src/Either.php:527:17 - Cannot reference $this in a pure context
src/Either.php:570:14 - Cannot reference $this in a pure context
src/Either.php:603:14 - Cannot reference $this in a pure context
src/Either.php:614:14 - Cannot reference $this in a pure context
src/Either.php:616:12 - Cannot reference $this in a pure context
src/Either.php:627:15 - Cannot reference $this in a pure context
src/Either.php:629:12 - Cannot reference $this in a pure context
src/Either.php:657:14 - Cannot reference $this in a pure context
src/Either.php:657:32 - Cannot call an impure function from a mutation-free context
src/Either.php:657:44 - Cannot reference $this in a pure context
src/Either.php:659:12 - Cannot reference $this in a pure context
src/Either.php:678:15 - Cannot reference $this in a pure context
src/Either.php:678:33 - Cannot call an impure function from a mutation-free context
src/Either.php:678:45 - Cannot reference $this in a pure context
src/Either.php:680:12 - Cannot reference $this in a pure context
src/Either.php:701:14 - Cannot reference $this in a pure context
src/Either.php:701:39 - Cannot reference $this in a pure context
src/Either.php:702:35 - Cannot reference $this in a pure context
src/Either.php:718:15 - Cannot reference $this in a pure context
src/Either.php:718:40 - Cannot reference $this in a pure context
src/Either.php:720:12 - Cannot reference $this in a pure context
src/Either.php:741:14 - Cannot reference $this in a pure context
src/Either.php:741:32 - Cannot reference $this in a pure context
src/Either.php:743:12 - Cannot reference $this in a pure context
src/Either.php:759:15 - Cannot reference $this in a pure context
src/Either.php:759:33 - Cannot reference $this in a pure context
src/Either.php:761:12 - Cannot reference $this in a pure context
src/Either.php:781:12 - Cannot reference $this in a pure context
src/Either.php:785:14 - Cannot reference $this in a pure context
src/Either.php:796:12 - Cannot reference $this in a pure context
src/Either.php:800:14 - Cannot reference $this in a pure context
src/Either.php:824:12 - Cannot reference $this in a pure context
src/Either.php:828:14 - Cannot call an impure function from a mutation-free context
src/Either.php:828:26 - Cannot reference $this in a pure context
src/Either.php:843:12 - Cannot reference $this in a pure context
src/Either.php:847:14 - Cannot call an impure function from a mutation-free context
src/Either.php:847:26 - Cannot reference $this in a pure context
src/Either.php:883:14 - Cannot reference $this in a pure context
src/Either.php:962:11 - Cannot call an impure function from a mutation-free context
src/Either.php:992:11 - Cannot call an impure function from a mutation-free context
src/Either.php:1064:11 - Cannot reference $this in a pure context
src/Either.php:1065:14 - Cannot reference $this in a pure context
src/Either.php:1068:24 - Cannot reference $this in a pure context
src/Either.php:1070:14 - Cannot reference $this in a pure context
src/Either.php:1073:25 - Cannot reference $this in a pure context
src/Option.php:36:14 - Cannot reference $this in a pure context
src/Option.php:62:14 - Cannot reference $this in a pure context
src/Option.php:63:12 - Cannot reference $this in a pure context
src/Option.php:91:14 - Cannot reference $this in a pure context
src/Option.php:92:12 - Cannot reference $this in a pure context
src/Option.php:93:12 - Cannot call an impure function from a mutation-free context
src/Option.php:117:14 - Cannot reference $this in a pure context
src/Option.php:118:12 - Cannot reference $this in a pure context
src/Option.php:146:14 - Cannot reference $this in a pure context
src/Option.php:147:12 - Cannot reference $this in a pure context
src/Option.php:148:23 - Cannot call an impure function from a mutation-free context
src/Option.php:170:14 - Cannot reference $this in a pure context
src/Option.php:171:12 - Cannot reference $this in a pure context
src/Option.php:197:14 - Cannot reference $this in a pure context
src/Option.php:198:12 - Cannot reference $this in a pure context
src/Option.php:199:12 - Cannot call an impure function from a mutation-free context
src/Option.php:237:14 - Cannot reference $this in a pure context
src/Option.php:238:12 - Cannot call an impure function from a mutation-free context
src/Option.php:238:18 - Cannot reference $this in a pure context
src/Option.php:239:12 - Cannot call an impure function from a mutation-free context
src/Option.php:261:12 - Cannot reference $this in a pure context
src/Option.php:265:7 - Cannot call an impure function from a mutation-free context
src/Option.php:265:13 - Cannot reference $this in a pure context
src/Option.php:288:11 - Cannot reference $this in a pure context
src/Option.php:292:7 - Cannot call an impure function from a mutation-free context
src/Option.php:333:14 - Cannot reference $this in a pure context
src/Option.php:366:17 - Cannot reference $this in a pure context
src/Option.php:409:14 - Cannot reference $this in a pure context
src/Option.php:446:14 - Cannot reference $this in a pure context
src/Option.php:482:14 - Cannot reference $this in a pure context
src/Option.php:482:34 - Cannot call an impure function from a mutation-free context
src/Option.php:482:46 - Cannot reference $this in a pure context
src/Option.php:484:12 - Cannot reference $this in a pure context
src/Option.php:502:14 - Cannot reference $this in a pure context
src/Option.php:502:41 - Cannot reference $this in a pure context
src/Option.php:504:12 - Cannot reference $this in a pure context
src/Option.php:523:14 - Cannot reference $this in a pure context
src/Option.php:523:34 - Cannot reference $this in a pure context
src/Option.php:525:12 - Cannot reference $this in a pure context
src/Option.php:545:12 - Cannot reference $this in a pure context
src/Option.php:549:14 - Cannot reference $this in a pure context
src/Option.php:574:12 - Cannot reference $this in a pure context
src/Option.php:578:14 - Cannot call an impure function from a mutation-free context
src/Option.php:578:26 - Cannot reference $this in a pure context
src/Option.php:655:11 - Cannot call an impure function from a mutation-free context
src/Option.php:686:11 - Cannot call an impure function from a mutation-free context
src/Option.php:757:11 - Cannot reference $this in a pure context
src/Option.php:758:14 - Cannot reference $this in a pure context
src/Option.php:761:25 - Cannot reference $this in a pure context
src/Result.php:60:14 - Cannot reference $this in a pure context
src/Result.php:69:14 - Cannot reference $this in a pure context
src/Result.php:82:14 - Cannot reference $this in a pure context
src/Result.php:95:14 - Cannot reference $this in a pure context
src/Result.php:111:17 - Cannot reference $this in a pure context
src/Result.php:129:14 - Cannot reference $this in a pure context
src/Result.php:148:17 - Cannot reference $this in a pure context
src/Result.php:166:17 - Cannot reference $this in a pure context
src/Result.php:194:17 - Cannot reference $this in a pure context
src/Result.php:217:14 - Cannot reference $this in a pure context
src/Result.php:232:7 - Cannot reference $this in a pure context
src/Result.php:247:7 - Cannot reference $this in a pure context
src/Result.php:268:17 - Cannot reference $this in a pure context
src/Result.php:290:17 - Cannot reference $this in a pure context
src/Result.php:312:17 - Cannot reference $this in a pure context
src/Result.php:332:14 - Cannot reference $this in a pure context
src/Result.php:358:17 - Cannot reference $this in a pure context
src/Result.php:369:17 - Cannot reference $this in a pure context
src/Result.php:380:17 - Cannot reference $this in a pure context
src/Result.php:400:17 - Cannot reference $this in a pure context
src/Result.php:420:17 - Cannot reference $this in a pure context
src/Result.php:437:17 - Cannot reference $this in a pure context
src/Result.php:454:17 - Cannot reference $this in a pure context
src/Result.php:466:14 - Cannot reference $this in a pure context
src/Result.php:477:14 - Cannot reference $this in a pure context
src/Result.php:492:14 - Cannot reference $this in a pure context
src/Result.php:591:17 - Cannot reference $this in a pure context
src/SimpleResult.php:61:14 - Cannot reference $this in a pure context
src/SimpleResult.php:70:14 - Cannot reference $this in a pure context
src/SimpleResult.php:81:11 - Cannot reference $this in a pure context
src/SimpleResult.php:83:17 - Cannot reference $this in a pure context
src/SimpleResult.php:86:16 - Cannot reference $this in a pure context
src/SimpleResult.php:109:17 - Cannot reference $this in a pure context
src/SimpleResult.php:130:20 - Cannot reference $this in a pure context
src/SimpleResult.php:130:35 - Type mixed should be a subtype of Throwable
src/SimpleResult.php:130:48 - Argument 1 of Optional\Either::orCreateLeft expects callable(Throwable|null):mixed, callable(Throwable):TOkay:Optional\SimpleResult as mixed provided
src/SimpleResult.php:152:17 - Cannot reference $this in a pure context
src/SimpleResult.php:181:20 - Cannot reference $this in a pure context
src/SimpleResult.php:208:14 - Cannot reference $this in a pure context
src/SimpleResult.php:208:29 - Type mixed should be a subtype of Throwable
src/SimpleResult.php:208:46 - Argument 2 of Optional\Either::match expects callable(Throwable|null):mixed, callable(Throwable):U:fn-optional\simpleresult::run as mixed provided
src/SimpleResult.php:223:7 - Cannot reference $this in a pure context
src/SimpleResult.php:238:7 - Cannot reference $this in a pure context
src/SimpleResult.php:238:22 - Type mixed should be a subtype of Throwable
src/SimpleResult.php:238:33 - Argument 1 of Optional\Either::matchRight expects callable(Throwable|null), callable(Throwable) provided
src/SimpleResult.php:259:17 - Cannot reference $this in a pure context
src/SimpleResult.php:281:20 - Cannot reference $this in a pure context
src/SimpleResult.php:281:35 - Type mixed should be a subtype of Throwable
src/SimpleResult.php:305:14 - Cannot reference $this in a pure context
src/SimpleResult.php:332:20 - Cannot reference $this in a pure context
src/SimpleResult.php:347:17 - Cannot reference $this in a pure context
src/SimpleResult.php:358:17 - Cannot reference $this in a pure context
src/SimpleResult.php:379:20 - Cannot reference $this in a pure context
src/SimpleResult.php:404:20 - Cannot reference $this in a pure context
src/SimpleResult.php:404:35 - Type mixed should be a subtype of Throwable
src/SimpleResult.php:404:49 - Argument 1 of Optional\Either::filterRightIf expects callable(Throwable|null):bool, callable(Throwable):bool provided
src/SimpleResult.php:454:14 - Cannot reference $this in a pure context
src/SimpleResult.php:465:14 - Cannot reference $this in a pure context
src/SimpleResult.php:480:14 - Cannot reference $this in a pure context
vendor/symfony/polyfill-mbstring/bootstrap80.php:125:88 - Syntax error, unexpected '=' on line 125
```

**Comment by jarstelfox** [comment]
Master has some psalm errors, I will check if this has the same errors or not.

**Comment by djmetzle** [comment]
CR :gear: but we need to get CI passing...

**Comment by davidrans** [comment]
I diffed the psalm failures on `master` on PHP 7  and this branch on PHP 8 and didn't see any differences:
```diff
▶  diff master_psalm php8_psalm 
618c618
< Checks took 0.49 seconds and used 83.712MB of memory
---
> Checks took 0.28 seconds and used 59.729MB of memory
```

Do we want to get psalm passing in this pull or save that for another?

**Comment by jarstelfox** [comment]
I’d save it for another. Part of the problem is I didn’t lock psalm to a version so at this point I think the last time it passed was 4.0

**Pull request merged**
